server:
  port: 8081

spring:
  application:
    name: auth-service

  profiles:
    include: secrets

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

notification:
  email:
    enabled: ${MAIL_ENABLED:true}
    from: ${MAIL_FROM:gdivya3007@gmail.com}

app:
  jwt:
    secret: ${JWT_SECRET:}
    access-token-expiration-ms: 86400000
    refresh-token-expiration-ms: 604800000

  oauth2:
    redirect-uri: http://localhost:4200/oauth2/success

springdoc:
  swagger-ui:
    path: /swagger-ui.html